#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo "Usage: $0 function_name arg1 arg2 ..."
  exit 0
fi
octavefunc=$1

if [ "$#" -gt 1 ]
then
 shift 1
 arglist=$1
fi

for i in `seq 2 $#`
do
 shift 1
 arglist="${arglist},$1"
done

echo Running: octave "$octavefunc($arglist)"
echo "$octavefunc($arglist); exit" | octave --no-gui
